In [45]:
import numpy as np 

In [46]:
arr=np.array([1,3,4,3])
arr

array([1, 3, 4, 3])

In [47]:
l=[[1,2,3],[3,4,53],[3,3,5]]
l

[[1, 2, 3], [3, 4, 53], [3, 3, 5]]

In [48]:
arr=np.array(l)
arr

array([[ 1,  2,  3],
       [ 3,  4, 53],
       [ 3,  3,  5]])

In [49]:
arr=np.arange(4)
arr

array([0, 1, 2, 3])

In [50]:
arr=np.zeros(8)
arr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

In [53]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
arr=np.linspace(2,5,3)
arr

array([2. , 3.5, 5. ])

In [55]:
np.random.rand(6)

array([0.52905697, 0.7445474 , 0.35287287, 0.47198328, 0.75675038,
       0.79462235])

In [56]:
np.random.randn(5)

array([-1.63448532,  0.73700337, -0.97054006, -1.23122547,  1.39630189])

In [57]:
np.random.randint(5)

4

In [58]:
np.random.randint(1,50,20)

array([14, 34,  7,  3,  7, 35, 20, 48,  8, 45, 37, 47,  3,  8,  7, 32, 22,
       46, 40, 31])

In [59]:
arr=np.array([[1,2,3],
     [2,3,4],
     [5,6,7]])
arr.shape
arr.size
arr.dtype

dtype('int32')

In [60]:
arr.mean()

3.6666666666666665

In [62]:
arr.min()

1

In [63]:
arr.max()

7

In [64]:
arr.sum()


33

In [65]:
arr.sum(axis=0)

array([ 8, 11, 14])

In [66]:
arr.argmin()

0

In [67]:
arr.argmax()

8

In [75]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [76]:
arr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [77]:
#NUMPY INDEXING AND SLICING FOR VECTORS

In [78]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [81]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [82]:
arr[1:19:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [83]:
#INDEXING AND SLICING IN MATRIXS

In [85]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [100]:
slice=arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [102]:
now=arr[:,3]
now

array([ 4,  9, 14, 19, 24, 29])

In [103]:
#BOOLEAN INDEXING

In [105]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [107]:
boolean=arr%3==0
boolean

array([False,  True, False, False,  True, False, False,  True, False,
       False])