In [1]:
import numpy as np 

In [6]:
arr=np.array([1,3,4,3])
arr

array([1, 3, 4, 3])

In [7]:
l=[[1,2,3],[3,4,53],[3,3,5]]
l

[[1, 2, 3], [3, 4, 53], [3, 3, 5]]

In [8]:
arr=np.array(l)
arr

array([[ 1,  2,  3],
       [ 3,  4, 53],
       [ 3,  3,  5]])

In [9]:
arr=np.arange(4)
arr

array([0, 1, 2, 3])

In [10]:
arr=np.zeros(8)
arr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

In [13]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])