In [1]:
import numpy as np

In [2]:
# NUMPY ARRAY OPERATION

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([2,3,5,6,7])


In [4]:
a1+a2

array([ 3,  5,  8, 10, 12])

In [13]:
a1**a2

array([    1,     8,   243,  4096, 78125])

In [14]:
#BRADCOSTING

In [15]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
arr=np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [20]:
arr+10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [21]:
arr*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [34]:
a1=np.arange(1,5).reshape(2,2)
a2=np.arange(11,15).reshape(2,2)

In [35]:
a1*a2

array([[11, 24],
       [39, 56]])

In [37]:
a1 @ a2

array([[37, 40],
       [85, 92]])

In [39]:
a1.T

array([[1, 3],
       [2, 4]])

In [40]:
np.dot(a1,a2)

array([[37, 40],
       [85, 92]])

In [41]:
#ADVANCED ARRAY MANUPULATION

In [43]:
np.vstack((a1,a2))#vertical stack

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [45]:
np.hstack((a1,a2))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [47]:
np.column_stack((a1,a2))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])