In [3]:
import numpy as np 


In [1]:
#EXESICS IN NUMPY OPERATION

In [2]:
# 1 VALID SODUKU

In [6]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [18]:
first=np.sum(s,axis=0)
first

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [19]:
sec=s.sum(axis=0)
sec

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [14]:
np.bool_(first==sec)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [20]:
s[:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
#general questions

In [21]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [22]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [36]:

#Find the average age of students.
np.mean(data[:,0])

18.4

In [35]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [37]:
#Find the highest Science mark.
np.max(data[:,2])

95

In [40]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>=90]

array([[19, 92, 88],
       [20, 90, 85]])

In [41]:
#Increase Math marks of all students by 5.
ok=data[:,1]+5
ok

array([90, 97, 81, 70, 95])

In [47]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [50]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:3],axis=0)

array([81.6, 83.2])

In [59]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])